### ISSUE TITLE
Game of Life example

### ISSUE THREAD

**Issue by bradrn** [catseye/ALPACA#7]
There is a Game of Life example on the README:

    state Dead  " "
      to Alive when 3 Alive and 5 Dead;
    state Alive "*"
      to Dead when 4 Alive or 7 Dead.

However, the rules for Life state that a live cell dies when adjacent to less than 2 or more than 3 alive cells. Wouldn't this correspond to the following definition?

    state Dead  " "
      to Alive when 3 Alive and 5 Dead;
    state Alive "*"
      to Dead when not (2 Alive or 3 Alive).

In addition, isn't the `5 Dead` in the `Dead` state redundant as we are using the Moore neighbourhood?

**Comment by OrangeNote** [comment]
In ALPACA when you read `when 3 Alive` it means "when there are at least 3 Alive cells in neighborhood". So if you want to say "when there are exactly 3 Alive cells" you have to write `when 3 Alive and 5 Dead`, that is equivalent to "at least 3 Alive and at least 5 Dead". 3 + 5 = 8, which is the cardinality of the default neighborhood: that means that there's exactly one (totalistic) configuration that can fulfill this condition.

So your rule `to Dead...` is wrong because I think it basically saying "when at most 1 Alive".

I hope I have answered your questions.

**Comment by bradrn** [comment]
Thank you! I missed that bit in the documentation:
> It evaluates to true only if the cell has **at least** that many neighbours of that state or class, in that neighbourhood.
